#!/usr/bin/env bash
# Render start command. If an Anthropic key is configured, runs the LLM gateway
# on localhost (never exposed publicly) and wires the booth app to it with a
# shared server token (GATEWAY_TOKEN, generated by Render). Without a key the
# booth runs alone and uses its built-in offline scorer.
set -euo pipefail

if [[ -n "${ANTHROPIC_ACTIVE_KEY_1:-}" ]]; then
  export GATEWAY_SERVER_TOKENS="booth:${GATEWAY_TOKEN}"
  export GATEWAY_HOST=127.0.0.1
  export GATEWAY_PORT=8100
  python -m gateway.main &
  export GATEWAY_URL="http://127.0.0.1:8100"
else
  unset GATEWAY_URL GATEWAY_TOKEN
fi

exec python app.py --host 0.0.0.0 --port "${PORT:-8000}"
