#!/usr/bin/env bash
# Render start command: runs the LLM gateway on localhost (never exposed
# publicly) and the booth app on Render's $PORT, wired together with one
# shared server token (GATEWAY_TOKEN, generated by Render).
set -euo pipefail

export GATEWAY_SERVER_TOKENS="booth:${GATEWAY_TOKEN}"
export GATEWAY_HOST=127.0.0.1
export GATEWAY_PORT=8100

python -m gateway.main &

export GATEWAY_URL="http://127.0.0.1:8100"
exec python app.py --host 0.0.0.0 --port "${PORT:-8000}"
